import type { Metadata } from "next";
import "./globals.css";
import { Outfit, Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

const outfitHeading = Outfit({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap", // I'm added from gemini
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap", // I'm added from gemini
});

export const metadata: Metadata = {
  title: "Create My Press App",
  description: "Generated by MD. ABDUL AZIZ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        inter.variable,
        outfitHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-right" />
        {/* Navbar */}
        {/* <Navbar /> */}

        {children}

        {/* Footer */}
      </body>
    </html>
  );
}
